name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: pnpm install
      - run: pnpm format:check
      - run: pnpm build
      - run: pnpm package

      # Upload Artifact
      - name: Upload Artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            ./dist/build.tar
